version: "3.8"

services:
  mysql-db:
    image: arm64v8/mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blockbuster
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - red_db
      - red_web

  web-server:
    build: .
    container_name: web-server
    depends_on:
      - mysql-db
    ports:
      - "8080:80"
    networks:
      - red_web
      - red_db

volumes:
  mysql_data:

networks:
  red_web:
    driver: bridge
  red_db:
    driver: bridge
